#!/usr/bin/env python3
"""
The changes to "Losing Lyumjev" since the version published on Diabettech, as one document for
editing the live post: where each change sits, the text, and the WordPress block HTML to paste.

The published version is the article at commit b6d7a42 with the author's two edits to the stand
paragraph, which are already live. Each change is found by matching blocks of the master article
against that version, so the document cannot drift from the master; the instructions for where each
block goes are written here and checked against the master's neighbouring blocks.

    python3 additions_since_publication.py      # writes additions/ (md, html) and prints the paths
"""
import difflib
import re
import subprocess
from pathlib import Path

from md_to_wordpress import convert

import docx
from docx.enum.text import WD_COLOR_INDEX
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Pt, RGBColor

HERE = Path(__file__).parent
OUT = HERE / "additions"
PUBLISHED = "b6d7a42"
STAND_EDITS = (("I should say where I stand. I have used", "I have used"),
               ("That is one person using experimental software.", "This is a major reason for my concern."))


def blocks(text):
    body = text.split("\n---\n", 1)[1]
    return [b.strip() for b in re.split(r"\n\s*\n", body) if b.strip()]


def norm(b):
    return " ".join(b.split())


def plain(b):
    """A block as a reader sees it: no heading marks, link text only."""
    return re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", norm(b)).lstrip("# ")


def main():
    pub = subprocess.run(["git", "show", f"{PUBLISHED}:article/diabettech-ultra-rapid-article.md"], cwd=HERE,
                         capture_output=True, text=True, check=True).stdout
    pub = " ".join(pub.split(" "))
    for old, new in STAND_EDITS:
        pub = re.sub(r"\s+".join(map(re.escape, old.split())), new, pub)
    a, b = blocks(pub), blocks((HERE / "diabettech-ultra-rapid-article.md").read_text())
    ops = [o for o in difflib.SequenceMatcher(None, [norm(x) for x in a], [norm(x) for x in b]).get_opcodes()
           if o[0] != "equal"]
    kind = lambda s: "the heading" if s.startswith("#") else "the paragraph"
    first = lambda s: f'{kind(s)} "{" ".join(plain(s).split()[:8])}"'
    last = lambda s: f'{kind(s)} "{" ".join(plain(s).split()[-6:])}"' if s.startswith("#") else \
        f'{kind(s)} ending "{" ".join(plain(s).split()[-6:])}"'

    changes = []
    for op, i1, i2, j1, j2 in ops:
        new = b[j1:j2]
        before, after = b[j1 - 1], (b[j2] if j2 < len(b) else None)
        if op == "replace":
            where = (f"Replace {first(a[i1])}... with the text below. It comes straight after {last(before)}.")
            title = "Replacement paragraph"
        else:
            where = f"Insert after {last(before)}" + (f" and before {first(after)}." if after else ".")
            title = ("New subsection" if new[0].startswith("#") else
                     "New paragraphs" if len(new) > 1 else "New paragraph")
        changes.append(dict(title=title, where=where, md=new))
    srcs = (HERE / "SOURCES.md").read_text().split("\n", 2)[2].strip()
    changes.append(dict(title="New: sources at the foot", where="Add at the very end of the post, after the closing "
                        f"paragraph \"...The sources follow.\": a heading \"Sources\" and the numbered list ({sum(1 for ln in srcs.splitlines() if re.match(r'[0-9]+[.] ', ln))} entries).",
                        md=["## Sources", srcs]))

    heads = {"Replacement paragraph": "", "New paragraph": "", "New subsection": ""}
    L = ["# Losing Lyumjev: changes since publication", "",
         "Each change below gives where it goes in the live post and the text as it reads. The WordPress block "
         "HTML for each change, in the same order and headed by the same instruction, is in "
         "changes_since_publication_wordpress.html; paste a block into the code editor (Options, Code editor) at "
         "the place given. The full regenerated post is "
         "diabettech-ultra-rapid-article-wordpress.html in the same folder, if replacing the whole body is easier. "
         "Generated by additions_since_publication.py from the master article; the published version is commit "
         f"{PUBLISHED} with the two edits to the stand paragraph already made in WordPress.", ""]
    H = []
    for n, c in enumerate(changes, 1):
        label = c["title"]
        if c["md"][0].startswith("### "):
            label += f": \"{c['md'][0][4:]}\""
        L += [f"## {n}. {label}", "", f"Where: {c['where']}", "", "Text:", ""]
        quoted = [x if re.match(r"\d+\. ", x) else "> " + norm(x) for x in c["md"]]
        L += ["\n>\n".join(q for q in quoted if q.startswith(">"))] + [q for q in quoted if not q.startswith(">")]
        L += [""]
        html = "\n\n".join(convert("\n\n".join(c["md"])))
        H += [f"<!-- ===== {n}. {label}. {c['where']} ===== -->", "", html, ""]
    OUT.mkdir(exist_ok=True)
    (OUT / "changes_since_publication.md").write_text("\n".join(L) + "\n")
    (OUT / "changes_since_publication_wordpress.html").write_text("\n".join(H) + "\n")
    write_docx(changes, OUT / "Losing Lyumjev - updates since publication.docx")
    print("\n".join(f"{n}. {c['title']} | {c['where']}" for n, c in enumerate(changes, 1)))


def add_link(par, text, url):
    """python-docx has no hyperlink API; this builds the w:hyperlink element with a relationship."""
    rid = par.part.relate_to(url, docx.opc.constants.RELATIONSHIP_TYPE.HYPERLINK, is_external=True)
    h = OxmlElement("w:hyperlink")
    h.set(qn("r:id"), rid)
    r = OxmlElement("w:r")
    rpr = OxmlElement("w:rPr")
    for tag, val in (("w:color", "1155CC"), ("w:u", "single")):
        e = OxmlElement(tag)
        e.set(qn("w:val"), val)
        rpr.append(e)
    r.append(rpr)
    t = OxmlElement("w:t")
    t.text = text
    t.set(qn("xml:space"), "preserve")
    r.append(t)
    h.append(r)
    par._p.append(h)


def add_text(par, text):
    """Markdown links and bare URLs become hyperlinks; everything else is plain text."""
    pat = re.compile(r"\[([^\]]+)\]\((https?://[^)]+)\)|(https?://[^\s)]+[^\s.,)])")
    pos = 0
    for m in pat.finditer(text):
        par.add_run(text[pos:m.start()])
        add_link(par, m.group(1) or m.group(3), m.group(2) or m.group(3))
        pos = m.end()
    par.add_run(text[pos:])


def write_docx(changes, path):
    d = docx.Document()
    st = d.styles["Normal"]
    st.font.name, st.font.size = "Georgia", Pt(11)
    d.add_heading("Losing Lyumjev: updates since publication", 0)
    d.add_paragraph("Each update below is headed with where it goes in the live post. Text in the shaded "
                    "\"Where to add it\" line is an instruction and is not part of the article; everything under it "
                    "is the text to add. Links are live and can be pasted into WordPress as they are. The WordPress "
                    "block HTML for the same updates is in changes_since_publication_wordpress.html in this folder.")
    for n, c in enumerate(changes, 1):
        label = c["title"] + (f": {c['md'][0][4:]}" if c["md"][0].startswith("### ") else "")
        d.add_heading(f"Update {n}. {label}", 1)
        w = d.add_paragraph()
        run = w.add_run("Where to add it: ")
        run.bold = True
        r2 = w.add_run(c["where"])
        for r in (run, r2):
            r.font.highlight_color = WD_COLOR_INDEX.YELLOW
        for b in c["md"]:
            if b.startswith("### ") or b.startswith("## "):
                h = d.add_heading(b.lstrip("# ").strip(), 3 if b.startswith("### ") else 2)
            elif re.match(r"\d+\. ", b):
                for item in re.split(r"\n(?=\d+\. )", b):
                    add_text(d.add_paragraph(style="List Number"), norm(re.sub(r"^\d+\. ", "", item)))
            else:
                add_text(d.add_paragraph(), norm(b))
    d.save(path)


if __name__ == "__main__":
    main()
