#!/usr/bin/env python3
"""
The changes to "Losing Lyumjev" since the version published on Diabettech, as one document for
editing the live post: where each change sits, the text, and the WordPress block HTML to paste.

The published version is the article at commit b6d7a42 with the author's two edits to the stand
paragraph, which are already live. Each change is found by matching blocks of the master article
against that version, so the document cannot drift from the master; the instructions for where each
block goes are written here and checked against the master's neighbouring blocks.

    python3 additions_since_publication.py      # writes additions/ (md, html) and prints the paths
"""
import difflib
import re
import subprocess
from pathlib import Path

from md_to_wordpress import convert

HERE = Path(__file__).parent
OUT = HERE / "additions"
PUBLISHED = "b6d7a42"
STAND_EDITS = (("I should say where I stand. I have used", "I have used"),
               ("That is one person using experimental software.", "This is a major reason for my concern."))


def blocks(text):
    body = text.split("\n---\n", 1)[1]
    return [b.strip() for b in re.split(r"\n\s*\n", body) if b.strip()]


def norm(b):
    return " ".join(b.split())


def plain(b):
    """A block as a reader sees it: no heading marks, link text only."""
    return re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", norm(b)).lstrip("# ")


def main():
    pub = subprocess.run(["git", "show", f"{PUBLISHED}:article/diabettech-ultra-rapid-article.md"], cwd=HERE,
                         capture_output=True, text=True, check=True).stdout
    pub = " ".join(pub.split(" "))
    for old, new in STAND_EDITS:
        pub = re.sub(r"\s+".join(map(re.escape, old.split())), new, pub)
    a, b = blocks(pub), blocks((HERE / "diabettech-ultra-rapid-article.md").read_text())
    ops = [o for o in difflib.SequenceMatcher(None, [norm(x) for x in a], [norm(x) for x in b]).get_opcodes()
           if o[0] != "equal"]
    kind = lambda s: "the heading" if s.startswith("#") else "the paragraph"
    first = lambda s: f'{kind(s)} "{" ".join(plain(s).split()[:8])}"'
    last = lambda s: f'{kind(s)} "{" ".join(plain(s).split()[-6:])}"' if s.startswith("#") else \
        f'{kind(s)} ending "{" ".join(plain(s).split()[-6:])}"'

    changes = []
    for op, i1, i2, j1, j2 in ops:
        new = b[j1:j2]
        before, after = b[j1 - 1], (b[j2] if j2 < len(b) else None)
        if op == "replace":
            where = (f"Replace {first(a[i1])}... with the text below. It comes straight after {last(before)}.")
            title = "Replacement paragraph"
        else:
            where = f"Insert after {last(before)}" + (f" and before {first(after)}." if after else ".")
            title = "New subsection" if new[0].startswith("#") else "New paragraph"
        changes.append(dict(title=title, where=where, md=new))
    srcs = (HERE / "SOURCES.md").read_text().split("\n", 2)[2].strip()
    changes.append(dict(title="New: sources at the foot", where="Add at the very end of the post, after the closing "
                        "paragraph \"...The sources follow.\": a heading \"Sources\" and the numbered list (60 entries).",
                        md=["## Sources", srcs]))

    heads = {"Replacement paragraph": "", "New paragraph": "", "New subsection": ""}
    L = ["# Losing Lyumjev: changes since publication", "",
         "Each change below gives where it goes in the live post and the text as it reads. The WordPress block "
         "HTML for each change, in the same order and headed by the same instruction, is in "
         "changes_since_publication_wordpress.html; paste a block into the code editor (Options, Code editor) at "
         "the place given. The full regenerated post is "
         "diabettech-ultra-rapid-article-wordpress.html in the same folder, if replacing the whole body is easier. "
         "Generated by additions_since_publication.py from the master article; the published version is commit "
         f"{PUBLISHED} with the two edits to the stand paragraph already made in WordPress.", ""]
    H = []
    for n, c in enumerate(changes, 1):
        label = c["title"]
        if c["md"][0].startswith("### "):
            label += f": \"{c['md'][0][4:]}\""
        L += [f"## {n}. {label}", "", f"Where: {c['where']}", "", "Text:", ""]
        quoted = [x if re.match(r"\d+\. ", x) else "> " + norm(x) for x in c["md"]]
        L += ["\n>\n".join(q for q in quoted if q.startswith(">"))] + [q for q in quoted if not q.startswith(">")]
        L += [""]
        html = "\n\n".join(convert("\n\n".join(c["md"])))
        H += [f"<!-- ===== {n}. {label}. {c['where']} ===== -->", "", html, ""]
    OUT.mkdir(exist_ok=True)
    (OUT / "changes_since_publication.md").write_text("\n".join(L) + "\n")
    (OUT / "changes_since_publication_wordpress.html").write_text("\n".join(H) + "\n")
    print("\n".join(f"{n}. {c['title']} | {c['where']}" for n, c in enumerate(changes, 1)))


if __name__ == "__main__":
    main()
