#!/usr/bin/env python3
"""
List price per 100 units of each long-acting analogue insulin in English primary care, against the
rapid-acting analogues, over August 2025 to July 2026. List price is net ingredient cost (NIC) from the
English Prescribing Dataset, the basic price before discount that the BNF prints as the NHS indicative
price, divided by units dispensed (quantity x units per device, as in history.py). Each brand's figure
blends its own mix of pens, cartridges and vials. Also reports the year each glargine biosimilar first
appears in the dispensing data, from the July series in epd_cache/basal_history.

Writes output/basal/PRICES.md and prices.csv.
"""
import json
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import pandas as pd

import epd_source as E
import history as H

HERE = Path(__file__).parent
C = HERE / "epd_cache" / "basal_nic"
OUT = HERE / "output" / "basal"
MONTHS = [f"EPD_SNOMED_{y}{m:02d}" for y, m in [(2025, m) for m in range(8, 13)] + [(2026, m) for m in range(1, 8)]]
LONG = ("0601012V0", "0601012Z0", "0601012X0")


def pull(res):
    f = C / f"{res}.json"
    if f.exists():
        return json.loads(f.read_text())
    like = " OR ".join(f"BNF_PRESENTATION_CODE LIKE '{p}%'" for p in LONG + ("0601011",))
    q = (f"SELECT BNF_PRESENTATION_CODE AS code, BNF_PRESENTATION_NAME AS name, "
         f"SUM(CAST(TOTAL_QUANTITY AS FLOAT64)) AS quantity, SUM(CAST(NIC AS FLOAT64)) AS nic "
         f"FROM `{res}` WHERE {like} GROUP BY 1, 2")
    rows = E.sql(q, res)
    C.mkdir(parents=True, exist_ok=True)
    f.write_text(json.dumps(rows))
    return rows


def brand(code, name):
    if code.startswith("0601011") and H.klass(code) == "human soluble":
        return None
    first = name.split()[0]
    if first == "Insulin":
        return "generic " + " ".join(name.split()[1:3])
    return first


def main():
    with ThreadPoolExecutor(7) as ex:
        d = pd.DataFrame([r for part in ex.map(pull, MONTHS) for r in part])
    d[["quantity", "nic"]] = d[["quantity", "nic"]].apply(pd.to_numeric)
    d["brand"] = [brand(c, n) for c, n in zip(d.code, d.name)]
    d = d.dropna(subset=["brand"])
    d["units"] = d.quantity * d.name.map(H.units_per_device)
    d["class"] = d.code.map(lambda c: "long-acting" if c.startswith(LONG) else "rapid-acting")
    g = d.groupby(["class", "brand"])[["units", "nic"]].sum()
    g["gbp_per_100u"] = g.nic / g.units * 100
    g = g[g.units > 1e6].sort_values(["class", "units"], ascending=[True, False])
    g.round(3).to_csv(OUT / "prices.csv")
    hist = HERE / "epd_cache" / "basal_history"
    seen = {}
    for f in sorted(hist.glob("*.json")):
        for r in json.loads(f.read_text()):
            for b in ("Abasaglar", "Semglee", "Toujeo", "Tresiba"):
                if r["name"].startswith(b):
                    seen.setdefault(b, f.stem[-6:-2])
    L = ["# Long-acting and rapid-acting analogue list prices, England: generated summary\n",
         "Generated by `basal_prices.py`. NIC per 100 units dispensed, August 2025 to July 2026; brands with "
         "over 1 million units.\n", "| class | brand | units (million) | list £ per 100 units |", "|---|---|---|---|"]
    for (c, b), r in g.iterrows():
        L.append(f"| {c} | {b} | {r.units / 1e6:,.0f} | {r.gbp_per_100u:.2f} |")
    L += ["", "First July (2014 to 2026) in which each product appears in English primary care dispensing: " +
          "; ".join(f"{k} {v}" for k, v in seen.items()) + "."]
    (OUT / "PRICES.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
