#!/usr/bin/env python3
"""
Uptake of the newer long-acting insulins and the ultra-rapid insulins in English primary care, set
side by side by years since each reached the market, so that Tresiba's earlier start (UK launch
2013) does not stand in for faster adoption.

One month a year, July 2014 to July 2026, from the English Prescribing Dataset (national, all
prescribers). Shares are of units: degludec and glargine 300 units/ml as a share of long-acting
analogue units (degludec, glargine 100 and 300, detemir); Fiasp and Lyumjev as a share of rapid-acting
analogue units. Years since launch are counted from the first month each product appears in
English primary care, taken from output/history for the rapid insulins; for degludec (January 2013)
and Toujeo (April 2015) the UK launch months are used, since the dataset used here starts in 2014.
That is a modelling choice and is stated in the output.

Writes output/basal/history.csv and HISTORY.md; caches under epd_cache/basal_history.
"""
import json
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import numpy as np
import pandas as pd

import epd_source as E
import history as H
from basal_vs_rapid import klass

HERE = Path(__file__).parent
C = HERE / "epd_cache" / "basal_history"
OUT = HERE / "output" / "basal"
LAUNCH = {"degludec": "2013-01", "glargine 300": "2015-04"}


def one(res):
    f = C / f"{res}.json"
    if f.exists():
        return json.loads(f.read_text()), res
    old = not res.startswith("EPD_SNOMED")
    code, name = ("BNF_CODE", "BNF_DESCRIPTION") if old else E.columns(res)[:2]
    q = (f"SELECT {code} AS code, {name} AS name, SUM(CAST(TOTAL_QUANTITY AS FLOAT64)) AS quantity FROM `{res}` "
         f"WHERE {code} LIKE '0601011%' OR {code} LIKE '0601012%' GROUP BY {code}, {name}")
    rows = E.sql(q, res)
    C.mkdir(parents=True, exist_ok=True)
    f.write_text(json.dumps(rows))
    return rows, res


def main():
    months = [f"EPD_{y}07" for y in range(2014, 2021)] + [f"EPD_SNOMED_{y}07" for y in range(2021, 2027)]
    with ThreadPoolExecutor(7) as ex:
        parts = list(ex.map(one, months))
    d = pd.concat([pd.DataFrame(r).assign(year=int(res[-6:-2])) for r, res in parts], ignore_index=True)
    d["quantity"] = pd.to_numeric(d.quantity)
    d["k"] = [klass(c, n) for c, n in zip(d.code, d.name)]
    d = d.dropna(subset=["k"])
    d["units"] = d.quantity * d.name.map(H.units_per_device)
    p = d.pivot_table(index="year", columns="k", values="units", aggfunc="sum").fillna(0)
    rapid = p[["Lyumjev", "Fiasp", "rapid other"]].sum(axis=1)
    basal = p[["degludec", "glargine 300", "glargine 100", "detemir"]].sum(axis=1)
    s = pd.DataFrame({"degludec": p.degludec / basal * 100, "glargine 300": p["glargine 300"] / basal * 100,
                      "Fiasp": p.Fiasp / rapid * 100, "Lyumjev": p.Lyumjev / rapid * 100})
    s.round(2).to_csv(OUT / "history.csv")
    hist = pd.read_csv(HERE / "output" / "history" / "national_by_presentation.csv", parse_dates=["date"])
    launch = dict(LAUNCH)
    for b, pre in (("Fiasp", "0601011A0BC"), ("Lyumjev", "0601011L0BD")):
        launch[b] = hist.loc[hist.code.str.startswith(pre), "date"].min().strftime("%Y-%m")
    rows = []
    for b in s.columns:
        start = pd.Timestamp(launch[b] + "-01")
        for y, v in s[b].items():
            t = (pd.Timestamp(f"{y}-07-01") - start).days / 365.25
            if t >= 0:
                rows.append(dict(product=b, years=t, share=v))
    r = pd.DataFrame(rows)
    L = ["# Newer long-acting and ultra-rapid insulins by years since launch, England: generated summary\n",
         "Generated by `basal_history.py`. July of each year, share of units within its class (long-acting "
         "analogue or rapid-acting analogue). Launch months: " +
         "; ".join(f"{k} {v}" for k, v in launch.items()) + " (degludec and glargine 300 are UK launch months; "
         "the rapid insulins are first months dispensed).\n",
         "| years since launch | degludec % | glargine 300 % | Fiasp % | Lyumjev % |", "|---|---|---|---|---|"]
    # Linear interpolation between July observations to whole years since launch; blank outside the
    # observed range (degludec before 1.5 years, which predates the dataset).
    for yrs in range(1, 14):
        cells = []
        for b in ("degludec", "glargine 300", "Fiasp", "Lyumjev"):
            g = r[r["product"] == b].sort_values("years")
            ok = g.years.min() <= yrs <= g.years.max()
            cells.append(f"{np.interp(yrs, g.years, g.share):.1f}" if ok else "")
        if any(cells):
            L.append(f"| {yrs} | " + " | ".join(cells) + " |")
    L += ["", "By calendar year (July):\n", "| year | degludec % | glargine 300 % | Fiasp % | Lyumjev % |",
          "|---|---|---|---|---|"]
    for y, v in s.iterrows():
        L.append(f"| {y} | {v.degludec:.1f} | {v['glargine 300']:.1f} | {v.Fiasp:.1f} | {v.Lyumjev:.1f} |")
    (OUT / "HISTORY.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
