#!/usr/bin/env python3
"""
The Fiasp FlexTouch pen, Fiasp's only disposable pen, went out of stock in the UK from April 2024
(DHSC medicine supply notification MSN/2024/027) and was discontinued in dm+d on 31 December 2025.
This measures its place in Fiasp dispensing before that, the move to Penfill cartridges, and the
growth of Fiasp's share before and after April 2024. The before and after windows are a modelling
choice: the 24 months before the shortage and every month since. Reads output/history/; writes
output/history/fiasp_pen.md.
"""
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).parent
FLEXTOUCH, PENFILL = "0601011A0BCAAAC", "0601011A0BCABAB"


def slope(s):
    t = (s.index - s.index[0]).days / 365.25
    return np.polyfit(t, s.values, 1)[0]


def main():
    p = pd.read_csv(HERE / "output" / "history" / "national_by_presentation.csv", parse_dates=["date"])
    p = p[p["class"] != "human soluble"]
    tot = p.groupby("date").units.sum()
    share = {b: (p[p.code.str.startswith(pre)].groupby("date").units.sum() / tot * 100).reindex(tot.index).fillna(0)
             for b, pre in (("Fiasp", "0601011A0BC"), ("Lyumjev", "0601011L0BD"))}
    fiasp = p[p.code.str.startswith("0601011A0BC")].groupby("date").units.sum()
    ft = p[p.code == FLEXTOUCH].groupby("date")
    pf = p[p.code == PENFILL].groupby("date")
    q = pd.DataFrame({"flextouch_items": ft["items"].sum(), "penfill_items": pf["items"].sum()}).resample("QS").sum()
    L = ["# Fiasp FlexTouch withdrawal: generated summary\n", "Generated by `fiasp_pen.py`.\n",
         f"FlexTouch share of Fiasp units, January to March 2024: "
         f"{ft.units.sum().loc['2024-01':'2024-03'].sum() / fiasp.loc['2024-01':'2024-03'].sum() * 100:.1f}%.\n",
         "| brand | share growth Apr 2022 to Mar 2024 (pp a year) | share growth Apr 2024 to latest (pp a year) |",
         "|---|---|---|"]
    for b, s in share.items():
        L.append(f"| {b} | {slope(s.loc['2022-04':'2024-03']):.2f} | {slope(s.loc['2024-04':]):.2f} |")
    L += ["", "| quarter | FlexTouch items | Penfill items |", "|---|---|---|"]
    for d, r in q.loc["2023":].iterrows():
        L.append(f"| {d:%Y} Q{(d.month - 1) // 3 + 1} | {r.flextouch_items:,.0f} | {r.penfill_items:,.0f} |")
    (HERE / "output" / "history" / "fiasp_pen.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
