#!/usr/bin/env python3
"""
Formulary position against ultra-rapid uptake across the UK: English ICBs (formulary_positions.csv,
coded in formulary_uptake.py), Scottish and Welsh health boards and Northern Ireland
(formulary_devolved/formulary_positions_devolved.csv). The same three-class rule is used throughout
(see formulary_uptake.py). Uptake is the ultra-rapid share of rapid-acting analogue units, July 2025
to June 2026 for Scotland, Wales and Northern Ireland (international/output/uk_boards.csv and
UK_SUMMARY.md), August 2025 to July 2026 for England.

The West of Scotland Formulary took effect on 30 July 2026, after the uptake window, so the five
boards it now covers are coded from the board formularies in force before it. Lanarkshire's earlier
formulary could not be read and is left out. Three codes rest on wording that reads either way; the
sensitivity analysis recodes Tayside ("2nd line bolus insulin for those who require a faster onset
of action") as second line, and Greater Glasgow and Clyde and Forth Valley (a requirement, applying
to every insulin, that a clinician experienced in diabetes recommends it) as open.

A finding the coding rule cannot capture: in several Scottish boards and in Cwm Taf Morgannwg and
Hywel Dda the specialist requirement applies to every mealtime insulin, including NovoRapid and
Trurapi, so "specialist" there does not mark ultra-rapid products out; in Betsi Cadwaladr and Swansea
Bay it does, and uptake there is still high. The rule was set for England, where restrictions attach to the
ultra-rapid products specifically, and is applied unchanged rather than refitted after seeing the
devolved data.

Writes output/formulary/uk_formulary_vs_uptake.csv and UK_SUMMARY.md.
"""
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).parent
OUT = HERE / "output" / "formulary"
ORDER = {"open": 0, "specialist": 1, "second_line_or_excluded": 2}
RNG = np.random.default_rng(20260930)
# Devolved areas: CSV row label fragment -> board name in uk_boards.csv.
AREAS = {
    "GGC Adult Formulary before WoS": ["Greater Glasgow and Clyde"],
    "Abbreviated Adult Joint Formulary, May 2026": ["Ayrshire and Arran"],
    "Forth Valley Formulary before WoS": ["Forth Valley"],
    "Joint Formulary 2025, before WoS": ["Dumfries and Galloway"],
    "Lothian (East Region": ["Lothian"], "Fife (East Region": ["Fife"], "Borders (East Region": ["Borders"],
    "Tayside (Tayside Area": ["Tayside"], "Grampian (Grampian Area": ["Grampian"],
    "Orkney (uses Grampian": ["Orkney"], "Shetland (uses Grampian": ["Shetland"],
    "Highland (Highland Formulary": ["Highland"], "Western Isles (uses Highland": ["Western Isles"],
    "Aneurin Bevan": ["Aneurin Bevan"], "Betsi Cadwaladr": ["Betsi Cadwaladr"], "Cardiff and Vale": ["Cardiff and Vale"],
    "Cwm Taf Morgannwg": ["Cwm Taf Morgannwg"], "Hywel Dda": ["Hywel Dda"], "Powys": ["Powys"],
    "Swansea Bay": ["Swansea Bay"],
}
SENSITIVITY = {"Tayside": "second_line_or_excluded", "Greater Glasgow and Clyde": "open", "Forth Valley": "open"}


def spearman_ci(d):
    r = d["rank"].corr(d.uptake, method="spearman")
    boots = []
    for _ in range(10000):
        s = d.sample(len(d), replace=True, random_state=RNG.integers(1 << 31))
        if s["rank"].nunique() > 1:
            boots.append(s["rank"].corr(s.uptake, method="spearman"))
    lo, hi = np.nanpercentile(boots, [2.5, 97.5])
    return r, lo, hi


def main():
    eng = pd.read_csv(OUT / "formulary_vs_uptake.csv")
    eng = eng[eng.icb_in_prescribing_data != "Norfolk and Suffolk"]
    rows = [dict(nation="England", area=r.icb_in_prescribing_data, restriction_class=r.restriction_class,
                 uptake=r.ultra_rapid_share_pct) for _, r in eng.iterrows()]
    dev = pd.read_csv(HERE / "formulary_devolved" / "formulary_positions_devolved.csv")
    boards = pd.read_csv(HERE / "international" / "output" / "uk_boards.csv").set_index("board")
    for frag, names in AREAS.items():
        m = dev[dev.area.str.contains(frag, regex=False)]
        assert len(m) == 1, (frag, len(m))
        for n in names:
            rows.append(dict(nation=m.nation.iloc[0], area=n, restriction_class=m.restriction_class.iloc[0],
                             uptake=boards.loc[n, "ultra_units_pct"]))
    ni = dev[dev.nation == "Northern Ireland"].iloc[0]
    summ = (HERE / "international" / "output" / "UK_SUMMARY.md").read_text()
    ni_up = float(next(l for l in summ.splitlines() if l.startswith("| Northern Ireland | ")).split("|")[2])
    rows.append(dict(nation="Northern Ireland", area="Northern Ireland", restriction_class=ni.restriction_class,
                     uptake=ni_up))
    d = pd.DataFrame(rows)
    d["rank"] = d.restriction_class.map(ORDER)
    d.to_csv(OUT / "uk_formulary_vs_uptake.csv", index=False)

    L = ["# Formulary position and ultra-rapid uptake across the UK: generated summary\n",
         "Generated by `formulary_uptake_uk.py`; coding rule and caveats in the script docstring.\n",
         "| nation | class | areas | median uptake % | range % |", "|---|---|---|---|---|"]
    for (n, c), g in d.groupby(["nation", "restriction_class"], sort=False):
        L.append(f"| {n} | {c} | {len(g)} | {g.uptake.median():.1f} | {g.uptake.min():.1f} to {g.uptake.max():.1f} |")
    L.append("")
    L += ["| set | areas | Spearman (restriction rank vs uptake) | bootstrap 95% interval |", "|---|---|---|---|"]
    for label, sub in (("England", d[d.nation == "England"]), ("Scotland", d[d.nation == "Scotland"]),
                       ("Wales", d[d.nation == "Wales"]), ("All UK", d)):
        r, lo, hi = spearman_ci(sub)
        L.append(f"| {label} | {len(sub)} | {r:.2f} | {lo:.2f} to {hi:.2f} |")
    s2 = d.copy()
    for a, c in SENSITIVITY.items():
        s2.loc[s2.area == a, "restriction_class"] = c
    s2["rank"] = s2.restriction_class.map(ORDER)
    for label, sub in (("Scotland, sensitivity", s2[s2.nation == "Scotland"]), ("All UK, sensitivity", s2)):
        r, lo, hi = spearman_ci(sub)
        L.append(f"| {label} | {len(sub)} | {r:.2f} | {lo:.2f} to {hi:.2f} |")
    L += ["", "| nation | area | class | uptake % |", "|---|---|---|---|"]
    for _, r in d.sort_values(["nation", "rank", "uptake"], ascending=[True, True, False]).iterrows():
        L.append(f"| {r.nation} | {r.area} | {r.restriction_class} | {r.uptake:.1f} |")
    (OUT / "UK_SUMMARY.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
