#!/usr/bin/env python3
"""
Ultra-rapid uptake by ICB against the formulary position of Fiasp and Lyumjev.

Formulary positions (formulary_positions.csv) were read from ICB and area prescribing committee
formularies on 30 September 2026 and coded by this rule, applied to the less restrictive of the
two products, since that is the most accessible ultra-rapid option in the area:
    open                    green, no clinical criteria, no specialist requirement
    specialist              specialist initiation or recommendation, or clinical criteria, without
                            requiring a standard analogue to have failed first
    second_line_or_excluded prior failure of a standard analogue required, restricted to pregnancy,
                            not listed, or not approved
The coding was done by one person who had already seen the uptake figures, so it is not blind.
Norfolk and Suffolk is excluded from the main comparison because only its Norfolk part was coded;
it is reported in a sensitivity line. Formulary pages mostly carry no date, so a position read in
September 2026 may postdate some of the prescribing it is compared with.

Writes output/formulary/.
"""
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).parent
OUT = HERE / "output" / "formulary"
ORDER = {"open": 0, "specialist": 1, "second_line_or_excluded": 2}
RNG = np.random.default_rng(20260930)


def norm(s):
    return (s.replace("NHS ", "").replace(" Integrated Care Board", "").replace(",", "").replace(" And ", " and ")
            .lower().strip())


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    f = pd.read_csv(HERE / "formulary_positions.csv")
    u = pd.read_csv(HERE / "output" / "icb_ultrarapid_share_last12m.csv")
    u["key"] = u.icb.map(norm)
    f["key"] = f.icb_in_prescribing_data.map(norm)
    d = f.merge(u[["key", "ultra_rapid_share_pct", "Fiasp_share_pct", "Lyumjev_share_pct"]], on="key", how="left")
    assert d.ultra_rapid_share_pct.notna().all(), d.loc[d.ultra_rapid_share_pct.isna(), "key"].tolist()
    d["rank"] = d.restriction_class.map(ORDER)
    d.to_csv(OUT / "formulary_vs_uptake.csv", index=False)

    main_set = d[d.icb_in_prescribing_data != "Norfolk and Suffolk"]
    L = ["# Formulary position and ultra-rapid uptake: generated summary\n",
         "Generated by `formulary_uptake.py`. Uptake is the ultra-rapid share of rapid-acting analogue "
         "units, August 2025 to July 2026. Coding rule and caveats in the script docstring.\n",
         "| class | ICBs | median % | range % |", "|---|---|---|---|"]
    for c in ORDER:
        g = main_set[main_set.restriction_class == c].ultra_rapid_share_pct
        L.append(f"| {c} | {len(g)} | {g.median():.1f} | {g.min():.1f} to {g.max():.1f} |")
    L.append("")

    # Spearman correlation between restriction rank and uptake, with a bootstrap interval over ICBs
    # and a permutation p-value. Ties in rank are handled by pandas' average ranking.
    def rho(x):
        return x["rank"].corr(x.ultra_rapid_share_pct, method="spearman")
    r = rho(main_set)
    boots = [rho(main_set.sample(len(main_set), replace=True, random_state=RNG.integers(1 << 31)))
             for _ in range(10000)]
    lo, hi = np.nanpercentile(boots, [2.5, 97.5])
    perm = [main_set["rank"].corr(pd.Series(RNG.permutation(main_set.ultra_rapid_share_pct.values),
                                            index=main_set.index), method="spearman") for _ in range(10000)]
    p = (np.sum(np.abs(perm) >= abs(r)) + 1) / (len(perm) + 1)
    L.append(f"Spearman correlation between restriction class and uptake, {len(main_set)} ICBs: "
             f"{r:.2f} (bootstrap 95% interval {lo:.2f} to {hi:.2f}; permutation p = {p:.4f}).\n")
    ns = d[d.icb_in_prescribing_data == "Norfolk and Suffolk"].iloc[0]
    L.append(f"Sensitivity: Norfolk and Suffolk, coded {ns.restriction_class} from its Norfolk part, had "
             f"{ns.ultra_rapid_share_pct:.1f}%.\n")
    L.append("| ICB | class | ultra-rapid % | Fiasp % | Lyumjev % |")
    L.append("|---|---|---|---|---|")
    for _, x in d.sort_values(["rank", "ultra_rapid_share_pct"], ascending=[True, False]).iterrows():
        L.append(f"| {x.icb_in_prescribing_data} | {x.restriction_class} | {x.ultra_rapid_share_pct:.1f} | "
                 f"{x.Fiasp_share_pct:.1f} | {x.Lyumjev_share_pct:.1f} |")
    (OUT / "SUMMARY.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
