#!/usr/bin/env python3
"""
Lyumjev on its own: its share of insulin lispro dispensed in English primary care by year since its
first dispensing (October 2020), and its cost per 100 units against Humalog. Lispro here is Lyumjev,
Humalog, Admelog, Insulin lispro Sanofi and generic lispro. Writes output/history/lyumjev_profile.md.
"""
from pathlib import Path

import pandas as pd

HERE = Path(__file__).parent


def main():
    p = pd.read_csv(HERE / "output" / "history" / "national_by_presentation.csv", parse_dates=["date"])
    p = p[p.code.str.startswith("0601011L0")]
    p["brand"] = p.code.str[:11].map({"0601011L0BD": "Lyumjev", "0601011L0BB": "Humalog"}).fillna("other lispro")
    start = p.loc[p.brand == "Lyumjev", "date"].min()
    p = p[p.date >= start]
    y = p.assign(y=p.date.dt.year).groupby(["y", "brand"]).agg(units=("units", "sum"), cost=("actual_cost", "sum")).unstack()
    share = (y["units"]["Lyumjev"] / y["units"].sum(axis=1) * 100).round(1)
    c = (y["cost"] / y["units"] * 100).round(2)
    L = ["# Lyumjev in English primary care: generated summary\n", f"Generated by `lyumjev_profile.py`. From {start:%B %Y}.\n",
         "| year | Lyumjev % of lispro units | Lyumjev cost per 100 units | Humalog cost per 100 units |", "|---|---|---|---|"]
    for yr in share.index:
        L.append(f"| {yr} | {share[yr]} | {c.loc[yr, 'Lyumjev']:.2f} | {c.loc[yr, 'Humalog']:.2f} |")
    (HERE / "output" / "history" / "lyumjev_profile.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
