#!/usr/bin/env python3
"""
The window before biosimilar rapid-acting insulin: Fiasp was first dispensed in English primary care
in February 2017 and Trurapi, the first biosimilar aspart, in June 2021. Over those months the only
alternative to an ultra-rapid insulin was its own originator, so a formulary or prescriber choosing
the standard-speed product could not have been choosing a cheaper insulin. This measures, for that
window: what the ultra-rapid products cost per 100 units against NovoRapid and Humalog, their share
of rapid-acting analogue units and items, and how much standard-speed analogue was dispensed.

The window boundaries are the first months each product appears in the data; they are a modelling
choice and are stated in the output. Reads output/history/national_by_presentation.csv; writes
output/history/prebiosimilar_window.md.
"""
from pathlib import Path

import pandas as pd

HERE = Path(__file__).parent
BRAND = {"0601011L0BD": "Lyumjev", "0601011A0BC": "Fiasp", "0601011L0BB": "Humalog",
         "0601011A0BB": "NovoRapid", "0601011P0BB": "Apidra", "0601011A0BD": "Trurapi"}


def main():
    p = pd.read_csv(HERE / "output" / "history" / "national_by_presentation.csv", parse_dates=["date"])
    p = p[p["class"] != "human soluble"].copy()
    p["brand"] = p.code.str[:11].map(BRAND)
    start = p.loc[p.brand == "Fiasp", "date"].min()
    end = p.loc[p.brand == "Trurapi", "date"].min() - pd.DateOffset(months=1)
    w = p[(p.date >= start) & (p.date <= end)]
    units = w.groupby("class").units.sum()
    items = w.groupby("class")["items"].sum()
    ultra_u = units.get("ultra-rapid", 0) / units.sum() * 100
    ultra_i = items.get("ultra-rapid", 0) / items.sum() * 100
    std_items = items.sum() - items.get("ultra-rapid", 0)
    cost = w.dropna(subset=["brand"]).groupby("brand").apply(lambda g: g.actual_cost.sum() / g.units.sum() * 100)
    yearly = w.assign(y=w.date.dt.year).pivot_table(index="y", columns="class", values="units", aggfunc="sum")
    yearly = (yearly["ultra-rapid"] / yearly.sum(axis=1) * 100).round(1)
    L = ["# The window before biosimilars: generated summary\n",
         f"Generated by `prebiosimilar_window.py`. Window: {start:%B %Y} (first Fiasp dispensing) to {end:%B %Y} "
         f"(month before first Trurapi dispensing), {w.date.nunique()} months.\n",
         f"Ultra-rapid share over the window: {ultra_u:.1f}% of rapid-acting analogue units and {ultra_i:.1f}% of items.",
         f"Standard-speed analogue items dispensed in the window: {std_items / 1e6:.2f} million.\n",
         "| brand | cost per 100 units over the window (pounds) |", "|---|---|"]
    for b in ("Fiasp", "NovoRapid", "Lyumjev", "Humalog", "Apidra"):
        if b in cost:
            L.append(f"| {b} | {cost[b]:.2f} |")
    L += ["", "Ultra-rapid share of units by calendar year within the window (partial years at each end): " +
          "; ".join(f"{y} {v}%" for y, v in yearly.items()) + "."]
    (HERE / "output" / "history" / "prebiosimilar_window.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
