#!/usr/bin/env python3
"""
Degludec (Tresiba) against the ultra-rapid insulins across the countries with product-level data:
England (and the other UK nations for the latest year), France, Denmark, Norway, Germany, Australia,
and the US Medicare Part D and Medicaid programmes.

Long-acting shares come from scoping/<country>/basal/basal_share_by_year.csv (each built by the script
in that folder, on the same volume basis as the country's rapid-acting series) and, for England, from
../output/basal/history.csv (July of each year). Ultra-rapid shares are output/intl_annual.csv. Shares
are of units within each class (long-acting analogue; rapid-acting analogue), except Australia, which
counts PBS prescriptions. Germany's ultra-rapid share is Fiasp only (its tables pool Lyumjev with
Liprolog), a lower bound. Norway has no ultra-rapid series, because Fiasp shares NovoRapid's ATC code.

Years since first dispensed counts from the first year a product has a non-zero share in that
country's own series; where a series starts after the product arrived (England degludec, launched
2013, series from 2014) the first observed year is marked as censored. Calendar years throughout,
Australia by financial year ending in the year shown.

Writes output/basal_intl.csv and BASAL_INTL.md.
"""
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).parent
SC = HERE / "scoping"
OUT = HERE / "output"
SERIES = {"France": ("france", "France"), "Denmark": ("denmark", "Denmark"), "Norway": ("norway", "Norway"),
          "Germany": ("germany", "Germany"), "Australia": ("australia", "Australia"),
          "US Medicare Part D": ("us", "US Medicare Part D"), "US Medicaid": ("us", "US Medicaid")}


def year(v):
    s = str(v)
    return 2000 + int(s[-2:]) if s.startswith("FY") else int(float(s))


def main():
    rows = []
    for label, (folder, name) in SERIES.items():
        b = pd.read_csv(SC / folder / "basal" / "basal_share_by_year.csv")
        b = b[b.country == name]
        for _, r in b.iterrows():
            if not (str(r.year).isdigit() or str(r.year).startswith("FY")):
                continue                        # partial periods such as "2026 Q1"
            rows.append(dict(country=label, year=year(r.year), degludec_pct=r.degludec_pct,
                             glargine300_pct=r.glargine300_pct))
    eng = pd.read_csv(HERE.parent / "output" / "basal" / "history.csv")
    for _, r in eng.iterrows():
        rows.append(dict(country="England", year=int(r.year), degludec_pct=r.degludec,
                         glargine300_pct=r["glargine 300"]))
    d = pd.DataFrame(rows)
    ultra = pd.read_csv(OUT / "intl_annual.csv")[["country", "year", "ultra_pct"]]
    # England's long-acting series is July of each year; its ultra series is calendar years. Both are
    # kept on their own basis; the year label is the calendar year in each case.
    d = d.merge(ultra, on=["country", "year"], how="outer").sort_values(["country", "year"])
    d.round(2).to_csv(OUT / "basal_intl.csv", index=False)

    def since(g, col, censored_from):
        g = g.dropna(subset=[col])
        pos = g[g[col] > 0]
        if pos.empty:
            return None, {}
        first = int(pos.year.min())
        cens = first == censored_from
        return first, {int(y - first + 1): v for y, v in zip(g.year, g[col]) if y >= first}

    L = ["# Degludec and the ultra-rapid insulins across countries: generated summary\n",
         "Generated by `basal_intl.py`; sources and bases in its docstring. Degludec % is of long-acting "
         "analogue volume; ultra-rapid % is of rapid-acting analogue volume (Germany: Fiasp only; Australia: "
         "prescriptions).\n", "## Latest year in each series\n",
         "| country | year | degludec % | glargine 300 % | ultra-rapid % |", "|---|---|---|---|---|"]
    for c, g in d.groupby("country", sort=False):
        gb = g.dropna(subset=["degludec_pct"])
        if gb.empty:
            continue
        r = gb.iloc[-1]
        u = g[(g.year == r.year)].ultra_pct
        u = u.iloc[0] if len(u) and not pd.isna(u.iloc[0]) else np.nan
        uy = g.dropna(subset=["ultra_pct"])
        if pd.isna(u) and len(uy):
            u_txt = f"{uy.ultra_pct.iloc[-1]:.1f} ({int(uy.year.iloc[-1])})"
        else:
            u_txt = "" if pd.isna(u) else f"{u:.1f}"
        g3 = "" if pd.isna(r.glargine300_pct) else f"{r.glargine300_pct:.1f}"
        L.append(f"| {c} | {int(r.year)} | {r.degludec_pct:.1f} | {g3} | {u_txt} |")
    L += ["", "## By years since first dispensed in each country\n",
          "Year 1 is the first year with a non-zero share. A first year marked * is the first year of the "
          "series, so the product may have arrived earlier.\n",
          "| country | degludec first year | ultra-rapid first year | degludec yr 3 | ultra yr 3 | degludec yr 5 | "
          "ultra yr 5 | degludec yr 7 | ultra yr 7 |", "|---|---|---|---|---|---|---|---|---|"]
    for c, g in d.groupby("country", sort=False):
        if not g.degludec_pct.notna().any():
            continue                                    # no long-acting series (Scotland, Wales, NI)
        start = int(g.dropna(subset=["degludec_pct"]).year.min())
        ustart = int(g.dropna(subset=["ultra_pct"]).year.min()) if g.ultra_pct.notna().any() else None
        fd, sd = since(g, "degludec_pct", start)
        fu, su = since(g, "ultra_pct", ustart)
        cell = lambda s, k: f"{s[k]:.1f}" if k in s and not pd.isna(s[k]) else ""
        fd_txt = "" if fd is None else f"{fd}{'*' if fd == start else ''}"
        fu_txt = "" if fu is None else f"{fu}{'*' if fu == ustart else ''}"
        L.append(f"| {c} | {fd_txt} | {fu_txt} | {cell(sd, 3)} | {cell(su, 3)} | {cell(sd, 5)} | {cell(su, 5)} | "
                 f"{cell(sd, 7)} | {cell(su, 7)} |")
    (OUT / "BASAL_INTL.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))


if __name__ == "__main__":
    main()
