#!/usr/bin/env python3
"""
Ultra-rapid share of rapid-acting analogue insulin by calendar year: the four UK nations, and the
countries with product-level open data (France, Denmark, Germany, Australia, US). Run after
uk_compare.py and each scoping/<country>/build_ultra_share.py.

The countries differ in coverage and basis, and the table records both: France and Denmark are
national community dispensing in units; Germany is statutory-insurance outpatient dispensing in
units, reported as a range because its published tables pool Lyumjev with Liprolog and omit
glulisine (lower bound Fiasp only, upper bound Fiasp plus the whole pooled lispro line); Australia
is PBS Section 85 prescriptions only, by financial year ending in the year shown, and Lyumjev is not
PBS-listed; the US figures cover Medicare Part D and Medicaid only. Partial years are dropped.

Writes international/output/intl_annual.csv, INTL_SUMMARY.md and figures/fig4_nations_countries.png.
"""
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).parent
OUT = HERE / "output"
SC = HERE / "scoping"
FIG = HERE.parent / "output" / "figures"
UK_COL = {"England": "#2a78d6", "Scotland": "#eb6834", "Northern Ireland": "#1baf7a", "Wales": "#eda100"}
INTL_COL = {"England": "#2a78d6", "France": "#e87ba4", "Denmark": "#008300", "Australia": "#4a3aa7"}


def uk_calendar():
    m = pd.read_csv(OUT / "uk_nations_monthly.csv", parse_dates=["date"])
    m["units_ultra"] = m.ultra_units_pct / 100 * m.analogue_units
    m["year"] = m.date.dt.year
    g = m.groupby(["nation", "year"]).agg(n=("date", "nunique"), u=("units_ultra", "sum"), t=("analogue_units", "sum"))
    g = g[g.n == 12]
    return pd.DataFrame({"country": g.index.get_level_values(0), "year": g.index.get_level_values(1),
                         "ultra_pct": (g.u / g.t * 100).values, "basis": "units, NHS community dispensing"})


def country(name, basis, keep=lambda y: True, year=lambda y: y):
    d = pd.read_csv(SC / name.lower() / "ultra_share_by_year.csv", dtype={"year": str})
    d = d[d.year.map(keep)]
    return pd.DataFrame({"country": name, "year": d.year.map(year).astype(int), "ultra_pct": d.ultra_pct.values,
                         "basis": basis})


def main():
    FIG.mkdir(parents=True, exist_ok=True)
    parts = [uk_calendar(),
             country("France", "units, reimbursed community dispensing", keep=str.isdigit),
             country("Denmark", "units, primary sector sales", keep=str.isdigit),
             country("Australia", "prescriptions, PBS Section 85, financial year ending",
                     year=lambda y: 2000 + int(y[-2:])),
             country("Germany", "units, statutory insurance; Fiasp only (lower bound)", keep=str.isdigit)]
    ger = pd.read_csv(SC / "germany" / "ultra_share_by_year.csv", dtype={"year": str})
    ger = ger[ger.year.str.isdigit()]
    us = pd.read_csv(SC / "us" / "ultra_share_by_year.csv", dtype={"year": str})
    us = us[us.year.str.isdigit() & ~us.denominator_note.str.contains("PROVISIONAL", na=False)]
    for label, key in (("US Medicaid", "Medicaid"), ("US Medicare Part D", "Part D")):
        u = us[us.basis.str.contains(key)]
        parts.append(pd.DataFrame({"country": label, "year": u.year.astype(int), "ultra_pct": u.ultra_pct.values,
                                   "basis": u.basis.values}))
    a = pd.concat(parts, ignore_index=True)
    a.round(2).to_csv(OUT / "intl_annual.csv", index=False)

    piv = a.pivot_table(index="year", columns="country", values="ultra_pct").round(1)
    order = ["England", "Scotland", "Wales", "Northern Ireland", "France", "Denmark", "Germany", "Australia",
             "US Medicare Part D", "US Medicaid"]
    piv = piv[[c for c in order if c in piv]]
    L = ["# UK nations and other countries: generated summary\n",
         "Generated by `intl_compare.py`. Ultra-rapid (Fiasp plus Lyumjev) % of rapid-acting analogue insulin, "
         "calendar years (Australia: financial year ending in the year shown). Germany is Fiasp only, a lower bound; "
         "its upper bound, adding the pooled Lyumjev and Liprolog line, is given below. Bases differ; see the script.\n",
         "| year | " + " | ".join(piv.columns) + " |", "|---|" + "---|" * len(piv.columns)]
    for y, r in piv.iterrows():
        L.append(f"| {y} | " + " | ".join("" if np.isnan(v) else f"{v:.1f}" for v in r) + " |")
    up = upper_bound()
    L += ["", "Germany upper bound: " + "; ".join(f"{y} {v:.1f}%" for y, v in up.items()) + "."]
    (OUT / "INTL_SUMMARY.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))
    figure(a, ger)


def figure(a, ger):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    plt.rcParams.update({"font.family": "serif", "font.serif": ["Times New Roman", "Times", "DejaVu Serif"],
                         "font.size": 10, "axes.spines.top": False, "axes.spines.right": False, "axes.grid": True,
                         "grid.color": "#e4e3df", "grid.linewidth": 0.6, "axes.axisbelow": True,
                         "axes.edgecolor": "#8a8984", "xtick.color": "#52514e", "ytick.color": "#52514e"})
    fig, axes = plt.subplots(1, 2, figsize=(7.2, 3.8), sharey=True)
    for ax, cols, title in ((axes[0], UK_COL, "UK nations"), (axes[1], INTL_COL, "Other countries")):
        if title == "Other countries":
            lo = ger.set_index(ger.year.astype(int)).ultra_pct
            up = upper_bound()
            if up is not None:
                ax.fill_between(lo.index, lo.values, up.reindex(lo.index).values, color="#d6d5cf", lw=0)
                ax.annotate("Germany (range)", (lo.index[-1], (lo.iloc[-1] + up.reindex(lo.index).iloc[-1]) / 2),
                            xytext=(4, 0), textcoords="offset points", va="center", fontsize=7.5, color="#52514e",
                            annotation_clip=False)
        for c, colour in cols.items():
            s = a[a.country == c].set_index("year").ultra_pct.sort_index()
            s = s[s.index >= 2016]
            ax.plot(s.index, s.values, color=colour, lw=2, marker="o", ms=3.5)
            ax.annotate(c, (s.index[-1], s.iloc[-1]), xytext=(4, 0), textcoords="offset points", va="center",
                        fontsize=7.5, color="#0b0b0b", annotation_clip=False)
        ax.set_title(title, loc="left", fontsize=10)
        ax.set_xlim(2016, 2026.2)
        ax.set_xticks([2017, 2019, 2021, 2023, 2025])
    axes[0].set_ylabel("Ultra-rapid % of rapid-acting analogue")
    axes[0].set_ylim(0, 35)
    fig.tight_layout()
    fig.subplots_adjust(wspace=0.45, right=0.86)
    fig.savefig(FIG / "fig4_nations_countries.png", dpi=220)
    plt.close(fig)


def upper_bound():
    f = SC / "germany" / "ultra_share_by_year.csv"
    d = pd.read_csv(f, dtype={"year": str})
    d = d[d.year.str.isdigit()]
    col = next((c for c in d.columns if "upper" in c.lower()), None)
    if col is None:
        m = d.denominator_note.str.extract(r"upper[^0-9]*([0-9.]+)")[0]
        if m.isna().all():
            return None
        return pd.Series(m.astype(float).values, index=d.year.astype(int))
    return pd.Series(d[col].astype(float).values, index=d.year.astype(int))


if __name__ == "__main__":
    main()
